added route protection and useAuth hook
bauerkamil/ZIWG_testo pull request #21
Opened 2024-04-21 22:04 UTC by bauerkamil

2024-04-28 14:51 UTC, Damian0401 requested changes

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/shared/hooks/auth/AuthProvider.tsx
> +  const user = window.localStorage.getItem("user");
to raczej powinien być jakiś const, a nie magic string

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/shared/hooks/auth/AuthReducer.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
nie ładnie tak lintera oszukiwać

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/main.tsx
>    // <React.StrictMode>
jeżeli nie chcecie używać strict mode to ja bym go całkowicie wyrzucił
https://bytedev.medium.com/code-comment-anti-patterns-and-why-the-comment-you-just-wrote-is-probably-not-needed-919a92cf6758

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/shared/hooks/auth/AuthProvider.tsx
> +  const user = window.localStorage.getItem("user");
w sumie zrobiłbym jakiś helper do korzystania z localstorage

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/shared/hooks/auth/AuthProvider.tsx
> +        window.open(AUTH_LINK, "_self");
nie ma jakiejś react'owej abstrakcji na używanie windows.open? może react-router coś ma

2024-04-28 14:51 UTC, Damian0401 commented on Frontend/src/shared/hooks/auth/AuthReducer.tsx
> +      window.localStorage.setItem(LocalStorageElements.User, user);
tak jak wyżej, dałbym to do jakiegoś helpera

2024-05-01 15:14 UTC, bauerkamil commented on Frontend/src/shared/hooks/auth/AuthProvider.tsx
> +  const user = window.localStorage.getItem("user");
done, denerwuje mnie tu brak angularowych serwisów xd

chciałem to w hooku zrobić, ale nie można ich zagnieżdżać

2024-05-01 15:14 UTC, bauerkamil commented on Frontend/src/shared/hooks/auth/AuthProvider.tsx
> +        window.open(AUTH_LINK, "_self");
https://simplefrontend.com/redirect-to-external-url-in-react/
react router pozwala tylko na wewnętrzne nawigowanie

2024-05-01 15:32 UTC, bauerkamil commented on Frontend/src/main.tsx
>    // <React.StrictMode>
done

2024-05-02 11:14 UTC, Damian0401 approved these changes

2024-05-02 11:27 UTC, merged